Rails-Booker2-main/config/routes.rb
Rails.application.routes.draw do
 root to:'homes#top'
  devise_for :users
  resources :books do 
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  post 'books/:id/edit' => 'books#update'
  
  resources :users
  get 'home/about' => 'homes#about'
  get 'users/home/about' => 'homes#about'
  post 'users/:id/edit' => 'users#update'
  
end

Rails-Booker2-main/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rails-Booker2-main/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
   def favorited_by?(user)
	 	favorites.where(user_id: user.id).exists?
	 end

  
  validates :title, presence:true
  validates :body, presence:true,length:{maximum: 200}
end

Rails-Booker2-main/app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence:true
end

Rails-Booker2-main/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

Rails-Booker2-main/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image
  
  # def favorited_by?(book)
  #   favorites.where(post_id: book.id).exists?
  # end
  
  validates :name, presence:true, uniqueness:true, length:{in: 2..20}
  validates :introduction,length:{maximum: 50}
end

Rails-Booker2-main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

Rails-Booker2-main/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
   def create
     book = Book.find(params[:book_id])
     @comment = current_user.book_comments.new(book_comment_params)
     @comment.book_id = book.id
    if @comment.save
      flash[:success] = "Successfully commented!"
      redirect_back(fallback_location: root_path)
    else
      flash[:notice] = "Failed to comment..."
      redirect_back(fallback_location: root_path)
    end
   end
   def destroy
    # @book = Book.find(params[:book_id])
    # @comment = @book.book_comments.find(params[:id])
     BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
     #@comment.destroy
     redirect_back(fallback_location: root_path)
   end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)

  end

end

Rails-Booker2-main/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :move_to_signed_in

  def index
    @books = Book.all
    @new_book= Book.new
    @user= current_user
    @favorite = Favorite.new
   #@user= User.find_by(params[:name])
   #@user= User.find_by(params[:introduction])
  end

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id

    if @new_book.save
      flash[:success] =  "You have created book successfully"
      redirect_to book_path(@new_book)
    else
      @books = Book.all
      @user = current_user
      #@user_name= User.find_by(params[:name])
     # @user_intro= User.find_by(params[:introduction])
      render 'index'
    end
  end

  def show
      @new_book = Book.new
      @book = Book.find(params[:id])
      @user = @book.user
      @book_comment = BookComment.new
      #@user= User.find(params[:id])
    # @user_name= User.find_by(params[:name])
    # @user_intro= User.find_by(params[:introduction])
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

  def update

    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private
  def book_params
      params.require(:book).permit(:title, :body)
  end
  def move_to_signed_in
    unless user_signed_in?
      #サインインしていないユーザーはログインページが表示される
      redirect_to  '/users/sigh_in'
    end
  end
end

Rails-Booker2-main/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
   
  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

Rails-Booker2-main/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
  
  def about
    
  end
  
end

Rails-Booker2-main/app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :move_to_signed_in

  def index
    @user= current_user
    @users = User.all
    @new_book= Book.new
    #@user_name= User.find_by(params[:id])
    #@user_intro= User.find_by(params[:introduction])
  end

  def show
    @user = User.find(params[:id])
    @new_book = Book.new
    @user_books = @user.books
    #@user_name= User.find_by(params[:id])
    #@user_intro= User.find_by(params[:introduction])
  end

  def edit
     @user = User.find(params[:id])
     unless @user.id == current_user.id
       redirect_to user_path(current_user.id)
     end
  end

  def update
  @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "You have updated User successfully."
      redirect_to user_path(@user)
    else
    render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

  def move_to_signed_in
    unless user_signed_in?
      #サインインしていないユーザーはログインページが表示される
      redirect_to  '/users/sign_in'
    end
  end
end

Rails-Booker2-main/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails-Booker2-main/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

Rails-Booker2-main/app/helpers/books_helper.rb
module BooksHelper
end

Rails-Booker2-main/app/helpers/favorites_helper.rb
module FavoritesHelper
end

Rails-Booker2-main/app/helpers/homes_helper.rb
module HomesHelper
end

Rails-Booker2-main/app/helpers/users_helper.rb
module UsersHelper
end

Rails-Booker2-main/app/views/books/edit.html.erb
<div class="container">
  <div class="errors">
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <p><% @book.errors.full_messages.each do |message| %></p>
    <ul>
    <li><%= message %></li>
    </ul>
      
    <% end %>
  <% end %>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      
      <%= form_with model:@book,local:true do |f| %>
      <div class="input-form">
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Opinion</p>
        <%= f.text_area :body %>
      </div>
      <div class="submit">
        <%= f.submit 'Update Book'%>
      </div>
      <% end %>
      <div class="back-links">
        
      <%= link_to 'Show', book_path %> | <%= link_to 'Back', books_path %>
      </div>
    </div>
  </div>
</div>

Rails-Booker2-main/app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="errors">
  <% if @new_book.errors.any? %>
    <h3><%= @new_book.errors.count %>errors prohibited this obj from being saved:</h3>
    <p><% @new_book.errors.full_messages.each do |message| %></p>
    <ul>
    <li><%= message %></li>
    </ul>

    <% end %>
  <% end %>
  </div>
  <div class="row">
   <div class="col-md-3">
<%= render 'users/user_info', user: @user, new_book: @new_book %>
    </div>

      <!--<a class="btn btn-outline-secondary btn-block fas fa-user-cog " href="/users/:id/edit"></a>-->



    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image-icon.jpg" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>

            <td>
              <% if book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fa fa-heart"style="color:red;"></i>
                  <%= book.favorites.count %>
                  <% end %>
                </p>
              <% else %>
                <p>
                  <%= link_to book_favorites_path(book), method: :post do %>
                  <i class="fa fa-heart" ></i> 
                  <%= book.favorites.count %>
                  <% end %>
                </p>
             <% end %>
            </td>
            <td><p>コメント数：<%= book.book_comments.count %></p></td>

          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

Rails-Booker2-main/app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
<div class="col-md-3">
<%= render 'users/user_info', user: @user, new_book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image-icon.jpg" %>
              <% end %>
              <div class="show-name">
                <%= link_to user_path(@user) do%>
                <%= @user.name %>
              <% end %>

              </div>

            </td>

            <td>
              <%= link_to book_path(@book) do %>
                 <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body %></td>

            <td>
              <% if @book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    <i class="fa fa-heart"style="color:red;"></i>
                    <%= @book.favorites.count %>
                  <% end %>
                </p>
              <% else %>
                <p>
                  <%= link_to book_favorites_path(@book), method: :post do %>
                    <i class="fa fa-heart" ></i>
                    <%= @book.favorites.count %>
                  <% end %>

                </p>
             <% end %></td>

            <% if @user == current_user %>
              <td>
                <%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success"  %>
                <%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-sm btn-success", "data-confirm":"本当に削除しますか？"  %>
              </td>
              <td><p>コメント数：<%= @book.book_comments.count %></p></td>
            <% end %>
          </tr>

        </tbody>
      </table>
      <div class="comments">

      <% @book.book_comments.each do |book_comment| %>
        <div class="comment_head">
          <%= link_to user_path(@user) do %>
            <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image-icon.jpg" %>
          <% end %>

          <%= book_comment.comment %>
          <% if  book_comment.user == current_user %>
            <%= link_to "Destroy" ,book_book_comment_path(@book,book_comment), method: :delete, class:"comment-destroy" %>
          <% end %>

        </div>
        <%= link_to user_path(@user) do %>
          <%= book_comment.user.name %>
        <% end %>
      <% end %>
      </div>
      <div class="new-comment">
        <%= form_with(model:[@book, @book_comment], local: true, class: "comment-form") do |f| %>
          <div class="comment-input">
          <%= f.text_area :comment, class:"comment-area" %>
          </div>
          <%= f.submit "送信" %>
       <% end %>
      </div>
    </div>
  </div>
</div>

Rails-Booker2-main/app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="px-3 mx-auto ">
      <h1> welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
    </div>
    </div>
  </div>
</main>

Rails-Booker2-main/app/views/homes/top.html.erb
<main><div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <!--<a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>-->
          <%= link_to "Log in", "/users/sign_in",class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
          <%= link_to "Sign up", "/users/sign_up",class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
        <div class="row">
          <!--<a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>-->
        </div>
      </div>
    </div>
  </div>
</div></main>

Rails-Booker2-main/app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

Rails-Booker2-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booker2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <!--<a class="navbar-brand" href="/"><span>Bookers</span></a>-->
      <%= link_to "Bookers", '/' ,class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
         
         
          <li></li>
          <li><%= link_to "Users",users_path,class:"fas fa-users nav-link text-light" %></li>
          <li><%= link_to "Books",books_path,class:"fas fa-book-open nav-link text-light" %></li>
          <li><%= link_to "logout", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %></li>

          <% else %>
         <li><%= link_to "Home", root_path,class:"fas fa-home nav-link text-light" %></li>
         <li><%= link_to "About", '/home/about',class:"fas fa-link nav-link text-light" %></li>
         <li><%= link_to "sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %></li>
         <li><%= link_to "login", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" %></li>
          <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= render 'layouts/notifications' %>
    <%= yield %>

    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
  </body>
</html>

Rails-Booker2-main/app/views/users/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li><a class="fas fa-home nav-link text-light" href="/users/28562"> Home</a></li>
          <% if user_signed_in? %>
          <li><a class="fas fa-users nav-link text-light" href="/users"> Users</a></li>
          <li><a class="fas fa-book-open nav-link text-light" href="/books"> Books</a></li>
          <li><a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out"> logout</a></li>
          <% else %>
          <li><a class="fas fa-users nav-link text-light" href="/about"> About</a></li>
          <li><a class="fas fa-book-open nav-link text-light" href="/books"> Books</a></li>
          <a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a>
          <% end %>
          
        </ul>
      </div>
    </div>
  </nav>
</header>

Rails-Booker2-main/app/views/users/_user_info.html.erb
      <h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, format: 'jpeg', size:"100x100",  fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>Introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">

        <%= link_to  edit_user_path(user.id),class:"btn btn-outline-secondary btn-block " do%>
        <i class="fas fa-user-cog"></i>
        <% end %>
      <!--<a class="btn btn-outline-secondary btn-block fas fa-user-cog " href="/users/:id/edit"></a>-->

      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: new_book,local:true do |f| %>
      <p>Title</p>
      <%= f.text_field :title %>
      <br>
      <p>Opinion</p>
      <%= f.text_area :body %>
      <br>
      <%= f.submit 'Create Book', class:"create-book" %>
      <% end %>

Rails-Booker2-main/app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <h1>User info</h1>
  <div class="errors">
  <% if @user.errors.any? %>
    <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
    <p><% @user.errors.full_messages.each do |message| %></p>
    <ul>
    <li><%= message %></li>
    </ul>
      
    <% end %>
  <% end %>
  </div>
      
     <%= form_with model:@user,local:true do |f| %>
      <div class="input-form">
        <p>Name</p>
        <%= f.text_field :name, class:"user-name" %>
        <p>Image</p>
        <%= f.attachment_field :profile_image %>
        
        <p>Introduction</p>
        <%= f.text_area :introduction,class:"user-intro" %>
      </div>
      <div class="submit">
        <%= f.submit 'Update User', class:"edit-input"%>
      </div>
     <% end %>
      
    </div>
  </div>
</div>

Rails-Booker2-main/app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
<%= render 'users/user_info', user: @user, new_book: @new_book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image-icon.jpg" %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to  user_path(user.id) do %>
              <p>Show</p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

Rails-Booker2-main/app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
<%= render 'users/user_info', user: @user, new_book: @new_book %>
    </div>


    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @user_books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image-icon.jpg" %>
              <% end %>

            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <td><p>コメント数：<%= book.book_comments.count %></p></td>
            <td><% if book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fa fa-heart"style="color:red;"></i>
                  <%= book.favorites.count %>
                  <% end %>
                </p>
              <% else %>
                <p>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="fa fa-heart" ></i>
                    <%= book.favorites.count %>
                  <% end %>

                </p>
             <% end %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>